#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${OUT:-${REPO_ROOT}/.webrtc_profile.env}"
ROLE="${ROLE:-auto}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      OUT="$2"
      shift 2
      ;;
    --role)
      ROLE="$2"
      shift 2
      ;;
    -h|--help)
      cat <<'USAGE'
Usage: scripts/detect_video_stack.sh [--role robot|machine|cloud|auto] [--out .webrtc_profile.env]

Detects the local video acceleration stack and writes a small shell env file
used by the WebRTC helper scripts.
USAGE
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

have() {
  command -v "$1" >/dev/null 2>&1
}

gst_has() {
  have gst-inspect-1.0 && gst-inspect-1.0 "$1" >/dev/null 2>&1
}

detect_machine_kind() {
  if grep -qi microsoft /proc/sys/kernel/osrelease 2>/dev/null; then
    echo "wsl2"
  elif [[ "$(uname -s)" == "Linux" ]]; then
    echo "linux"
  else
    echo "unknown"
  fi
}

quote_env() {
  local value="$1"
  value="${value//\'/\'\\\'\'}"
  printf "'%s'" "${value}"
}

MACHINE_KIND="$(detect_machine_kind)"
ARCH="$(uname -m)"
HAS_GSTREAMER=0
HAS_WEBRTCBIN=0
HAS_NICE=0
HAS_NVIDIA=0
HAS_DRI=0
VIDEO_ACCEL="none"
VIDEO_DECODER_ACCEL="none"
GST_H264_ENCODER_NAME=""
GST_H264_ENCODER_PROPS=""
GST_H264_DECODER_NAME=""
GST_H264_DECODER_PROPS=""
VIDEO_BITRATE_KBIT="${VIDEO_BITRATE_KBIT:-8000}"
NOTES=()

if [[ "${ROLE}" == "cloud" ]]; then
  mkdir -p "$(dirname "${OUT}")"
  {
    echo "# Generated by scripts/detect_video_stack.sh"
    echo "ROLE=$(quote_env "${ROLE}")"
    echo "MACHINE_KIND=$(quote_env "${MACHINE_KIND}")"
    echo "ARCH=$(quote_env "${ARCH}")"
    echo "HAS_GSTREAMER=0"
    echo "HAS_WEBRTCBIN=0"
    echo "HAS_NICE=0"
    echo "HAS_NVIDIA=0"
    echo "HAS_DRI=0"
    echo "VIDEO_ACCEL='none'"
    echo "VIDEO_DECODER_ACCEL='none'"
    echo "GST_H264_ENCODER_NAME=''"
    echo "GST_H264_ENCODER_PROPS=''"
    echo "GST_H264_DECODER_NAME=''"
    echo "GST_H264_DECODER_PROPS=''"
    echo "VIDEO_BITRATE_KBIT=${VIDEO_BITRATE_KBIT}"
  } > "${OUT}"
  echo "Wrote ${OUT}"
  echo "Cloud role: skipped media hardware detection; hub mode relays signaling only."
  exit 0
fi

if have gst-inspect-1.0; then
  HAS_GSTREAMER=1
fi

if gst_has webrtcbin; then
  HAS_WEBRTCBIN=1
else
  NOTES+=("GStreamer webrtcbin is missing; install gstreamer1.0-plugins-bad for native WebRTC media.")
fi

if gst_has nice; then
  HAS_NICE=1
else
  NOTES+=("GStreamer libnice plugin is missing; install gstreamer1.0-nice for WebRTC ICE/media transport.")
fi

if have nvidia-smi && nvidia-smi >/dev/null 2>&1; then
  HAS_NVIDIA=1
fi

if [[ -d /dev/dri ]]; then
  HAS_DRI=1
fi

probe_encoder() {
  local name="$1"
  local props="$2"
  local log="/tmp/horus_connector_${name}_probe.log"
  read -r -a prop_array <<< "${props}"
  local cmd=(
    gst-launch-1.0 -q
    videotestsrc is-live=true num-buffers=8 pattern=smpte
    '!'
    'video/x-raw,width=640,height=360,framerate=30/1'
    '!'
    queue max-size-buffers=1 max-size-bytes=0 max-size-time=0 leaky=downstream
    '!'
    videoconvert
    '!'
    "${name}"
  )
  for prop in "${prop_array[@]}"; do
    [[ -n "${prop}" ]] && cmd+=("${prop}")
  done
  cmd+=('!' h264parse config-interval=-1 '!' fakesink sync=false)
  "${cmd[@]}" >"${log}" 2>&1
}

try_encoder() {
  local accel="$1"
  local name="$2"
  local props="$3"
  if ! gst_has "${name}"; then
    return 1
  fi
  if probe_encoder "${name}" "${props}"; then
    VIDEO_ACCEL="${accel}"
    GST_H264_ENCODER_NAME="${name}"
    GST_H264_ENCODER_PROPS="${props}"
    return 0
  fi
  NOTES+=("${name} exists but failed a short encode probe; skipping it.")
  return 1
}

if ! try_encoder "nvidia-nvenc" "nvh264enc" "rc-mode=cbr zerolatency=true bframes=0 gop-size=30 bitrate=${VIDEO_BITRATE_KBIT} aud=false" \
  && ! try_encoder "nvidia-nvenc" "nvautogpuh264enc" "bitrate=${VIDEO_BITRATE_KBIT} gop-size=30 aud=false" \
  && ! try_encoder "nvidia-nvenc" "nvcudah264enc" "bitrate=${VIDEO_BITRATE_KBIT} gop-size=30 aud=false" \
  && ! try_encoder "nvidia-v4l2" "nvv4l2h264enc" "bitrate=$((VIDEO_BITRATE_KBIT * 1000)) control-rate=1 iframeinterval=30 insert-sps-pps=true" \
  && ! try_encoder "vaapi" "vah264enc" "bitrate=${VIDEO_BITRATE_KBIT} keyframe-period=30 tune=low-power" \
  && ! try_encoder "vaapi" "vaapih264enc" "bitrate=${VIDEO_BITRATE_KBIT} keyframe-period=30 tune=low-power" \
  && ! try_encoder "v4l2-m2m" "v4l2h264enc" "extra-controls=controls,video_bitrate=$((VIDEO_BITRATE_KBIT * 1000)),h264_i_frame_period=30" \
  && ! try_encoder "cpu-x264" "x264enc" "tune=zerolatency speed-preset=ultrafast key-int-max=30 bitrate=${VIDEO_BITRATE_KBIT} byte-stream=true bframes=0" \
  && ! try_encoder "cpu-openh264" "openh264enc" "bitrate=$((VIDEO_BITRATE_KBIT * 1000)) gop-size=30"; then
  NOTES+=("No H.264 encoder element found; install NVIDIA, VAAPI, V4L2, x264, or OpenH264 GStreamer plugins.")
fi

probe_decoder() {
  local name="$1"
  local props="$2"
  local log="/tmp/horus_connector_${name}_decode_probe.log"
  read -r -a prop_array <<< "${props}"
  local cmd=(
    gst-launch-1.0 -q
    videotestsrc num-buffers=8 pattern=smpte
    '!'
    'video/x-raw,width=640,height=360,framerate=30/1'
    '!'
    x264enc tune=zerolatency speed-preset=ultrafast key-int-max=30
    '!'
    h264parse
    '!'
    "${name}"
  )
  for prop in "${prop_array[@]}"; do
    [[ -n "${prop}" ]] && cmd+=("${prop}")
  done
  cmd+=('!' videoconvert '!' fakesink sync=false)
  "${cmd[@]}" >"${log}" 2>&1
}

try_decoder() {
  local accel="$1"
  local name="$2"
  local props="$3"
  if ! gst_has "${name}"; then
    return 1
  fi
  if probe_decoder "${name}" "${props}"; then
    VIDEO_DECODER_ACCEL="${accel}"
    GST_H264_DECODER_NAME="${name}"
    GST_H264_DECODER_PROPS="${props}"
    return 0
  fi
  NOTES+=("${name} exists but failed a short decode probe; skipping it.")
  return 1
}

if ! try_decoder "nvidia-nvdec" "nvh264dec" "" \
  && ! try_decoder "nvidia-v4l2" "nvv4l2decoder" "" \
  && ! try_decoder "vaapi" "vah264dec" "" \
  && ! try_decoder "vaapi" "vaapih264dec" "" \
  && ! try_decoder "v4l2-m2m" "v4l2slh264dec" "" \
  && ! try_decoder "v4l2-m2m" "v4l2h264dec" "" \
  && ! try_decoder "cpu-libav" "avdec_h264" "" \
  && ! try_decoder "cpu-openh264" "openh264dec" ""; then
  NOTES+=("No H.264 decoder element found; install NVIDIA, VAAPI, V4L2, libav, or OpenH264 GStreamer plugins.")
fi

mkdir -p "$(dirname "${OUT}")"
{
  echo "# Generated by scripts/detect_video_stack.sh"
  echo "ROLE=$(quote_env "${ROLE}")"
  echo "MACHINE_KIND=$(quote_env "${MACHINE_KIND}")"
  echo "ARCH=$(quote_env "${ARCH}")"
  echo "HAS_GSTREAMER=${HAS_GSTREAMER}"
  echo "HAS_WEBRTCBIN=${HAS_WEBRTCBIN}"
  echo "HAS_NICE=${HAS_NICE}"
  echo "HAS_NVIDIA=${HAS_NVIDIA}"
  echo "HAS_DRI=${HAS_DRI}"
  echo "VIDEO_ACCEL=$(quote_env "${VIDEO_ACCEL}")"
  echo "VIDEO_DECODER_ACCEL=$(quote_env "${VIDEO_DECODER_ACCEL}")"
  echo "GST_H264_ENCODER_NAME=$(quote_env "${GST_H264_ENCODER_NAME}")"
  echo "GST_H264_ENCODER_PROPS=$(quote_env "${GST_H264_ENCODER_PROPS}")"
  echo "GST_H264_DECODER_NAME=$(quote_env "${GST_H264_DECODER_NAME}")"
  echo "GST_H264_DECODER_PROPS=$(quote_env "${GST_H264_DECODER_PROPS}")"
  echo "VIDEO_BITRATE_KBIT=${VIDEO_BITRATE_KBIT}"
} > "${OUT}"

echo "Wrote ${OUT}"
echo "Machine: ${MACHINE_KIND} ${ARCH}"
echo "GStreamer: ${HAS_GSTREAMER}, webrtcbin: ${HAS_WEBRTCBIN}, nice: ${HAS_NICE}, NVIDIA: ${HAS_NVIDIA}, /dev/dri: ${HAS_DRI}"
if [[ -n "${GST_H264_ENCODER_NAME}" ]]; then
  echo "Selected H.264 encoder: ${GST_H264_ENCODER_NAME} (${VIDEO_ACCEL})"
  echo "Encoder properties: ${GST_H264_ENCODER_PROPS}"
else
  echo "Selected H.264 encoder: none"
fi
if [[ -n "${GST_H264_DECODER_NAME}" ]]; then
  echo "Selected H.264 decoder: ${GST_H264_DECODER_NAME} (${VIDEO_DECODER_ACCEL})"
  echo "Decoder properties: ${GST_H264_DECODER_PROPS}"
else
  echo "Selected H.264 decoder: none"
fi

if [[ ${#NOTES[@]} -gt 0 ]]; then
  printf '\nNotes:\n'
  for note in "${NOTES[@]}"; do
    printf ' - %s\n' "${note}"
  done
fi
