#!/usr/bin/env python3
"""Render a Zenoh JSON5 config with optional TLS settings."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path


def json5_string(value: str) -> str:
    return json.dumps(value)


def tls_block(args: argparse.Namespace, indent: str) -> list[str]:
    fields: list[tuple[str, str | bool]] = []
    if args.root_ca:
        fields.append(("root_ca_certificate", args.root_ca))
    if args.listen_private_key:
        fields.append(("listen_private_key", args.listen_private_key))
    if args.listen_certificate:
        fields.append(("listen_certificate", args.listen_certificate))
    if args.connect_private_key:
        fields.append(("connect_private_key", args.connect_private_key))
    if args.connect_certificate:
        fields.append(("connect_certificate", args.connect_certificate))
    if args.enable_mtls:
        fields.append(("enable_mtls", True))
    if args.verify_name_on_connect is not None:
        fields.append(("verify_name_on_connect", args.verify_name_on_connect))
    if args.close_link_on_expiration:
        fields.append(("close_link_on_expiration", True))

    if not fields:
        return []

    lines = [f"{indent}tls: {{"]
    for key, value in fields:
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        else:
            rendered = json5_string(value)
        lines.append(f"{indent}  {key}: {rendered},")
    lines.append(f"{indent}}},")
    return lines


def insert_tls(text: str, block: list[str]) -> str:
    if not block:
        return text
    if re.search(r"(?m)^\s*tls\s*:\s*\{", text):
        return text

    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = re.match(r"^(\s*)link\s*:\s*\{\s*(?://.*)?$", line)
        if not match:
            continue
        indent = match.group(1) + "  "
        adjusted = []
        base_indent = len(block[0]) - len(block[0].lstrip())
        for item in block:
            item_indent = len(item) - len(item.lstrip())
            adjusted.append(" " * (len(indent) + item_indent - base_indent) + item.lstrip())
        lines[index + 1:index + 1] = adjusted
        return "\n".join(lines) + "\n"

    raise SystemExit("Could not find transport.link block in Zenoh config; cannot inject TLS settings.")


def parse_bool(value: str | None) -> bool | None:
    if value is None or value == "":
        return None
    lowered = value.strip().lower()
    if lowered in {"1", "true", "yes", "on"}:
        return True
    if lowered in {"0", "false", "no", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"Invalid boolean value: {value}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--root-ca", default="")
    parser.add_argument("--listen-private-key", default="")
    parser.add_argument("--listen-certificate", default="")
    parser.add_argument("--connect-private-key", default="")
    parser.add_argument("--connect-certificate", default="")
    parser.add_argument("--enable-mtls", action="store_true")
    parser.add_argument("--verify-name-on-connect", type=parse_bool, default=None)
    parser.add_argument("--close-link-on-expiration", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    base = Path(args.base).expanduser().resolve()
    out = Path(args.out).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    if not base.exists():
        raise SystemExit(f"Missing base Zenoh config: {base}")

    text = base.read_text(encoding="utf-8")
    block = tls_block(args, "      ")
    if block:
        rendered = insert_tls(text, block)
        rendered = "// Generated by scripts/render_zenoh_config.py. Do not edit.\n" + rendered
        out.write_text(rendered, encoding="utf-8")
    else:
        shutil.copy2(base, out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
