#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${HORUS_ENV:-${ROOT}/.env}"
PROFILE_FILE="${ROOT}/.zenoh_tls_profile.env"
ACTION="${1:-auto}"
ACTION="${ACTION%$'\r'}"

RESET="\033[0m"
BOLD="\033[1m"
FG_GREEN="\033[38;5;48m"
FG_YELLOW="\033[38;5;214m"
FG_RED="\033[38;5;203m"
FG_CYAN="\033[38;5;51m"
FG_MUTED="\033[38;5;244m"

log_success() { echo -e "${FG_GREEN}OK${RESET}      $*"; }
log_info() { echo -e "${FG_CYAN}Info${RESET}    $*"; }
log_warn() { echo -e "${FG_YELLOW}Warning${RESET} $*"; }
log_error() { echo -e "${FG_RED}Error${RESET}   $*" >&2; }

usage() {
  echo -e "\n${BOLD}${FG_CYAN}Zenoh QUIC TLS setup${RESET}"
  echo -e "${FG_MUTED}Generate or install the TLS material required by Zenoh QUIC.${RESET}\n"
  echo -e "${BOLD}Usage${RESET}"
  echo -e "  ./scripts/setup_zenoh_tls.sh server       Generate listener cert/key on cloud or direct machine"
  echo -e "  ./scripts/setup_zenoh_tls.sh client CERT  Install the hub/listener public cert on a robot or machine"
  echo -e "  ./scripts/setup_zenoh_tls.sh status       Show the active local TLS profile\n"
}

trim_spaces() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value}"
}

load_key_value_file() {
  local file="$1"
  local line key value
  [[ -f "${file}" ]] || return 0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%$'\r'}"
    line="$(trim_spaces "${line}")"
    [[ -z "${line}" || "${line}" == \#* ]] && continue
    if [[ "${line}" =~ ^export[[:space:]]+(.+)$ ]]; then
      line="${BASH_REMATCH[1]}"
    fi
    if [[ ! "${line}" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      log_warn "Ignoring invalid config line in ${file}: ${line}"
      continue
    fi
    key="${BASH_REMATCH[1]}"
    value="$(trim_spaces "${BASH_REMATCH[2]}")"
    if [[ "${#value}" -ge 2 ]]; then
      if [[ "${value:0:1}" == "'" && "${value: -1}" == "'" ]]; then
        value="${value:1:${#value}-2}"
      elif [[ "${value:0:1}" == '"' && "${value: -1}" == '"' ]]; then
        value="${value:1:${#value}-2}"
      fi
    fi
    printf -v "${key}" '%s' "${value}"
    export "${key}"
  done < "${file}"
}

shell_quote_value() {
  local value="$1"
  printf "'%s'" "${value//\'/\'\\\'\'}"
}

tls_dir() {
  echo "${ZENOH_TLS_DIR:-${HOME}/.config/horus_connector/zenoh_tls}"
}

normalize_host() {
  local value="$1"
  value="${value#quic/}"
  value="${value#tcp/}"
  value="${value%%:*}"
  value="${value%%/*}"
  value="${value%%\?*}"
  printf '%s' "${value}"
}

is_ipv4() {
  [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
}

add_unique() {
  local -n array_ref="$1"
  local value="$2"
  local item
  [[ -z "${value}" ]] && return 0
  value="$(normalize_host "${value}")"
  [[ -z "${value}" ]] && return 0
  for item in "${array_ref[@]}"; do
    [[ "${item}" == "${value}" ]] && return 0
  done
  array_ref+=("${value}")
}

write_profile() {
  local root_ca="$1"
  local listen_key="$2"
  local listen_cert="$3"
  {
    echo "# Generated by scripts/setup_zenoh_tls.sh"
    echo "ZENOH_TLS_DIR=$(shell_quote_value "$(tls_dir)")"
    echo "ZENOH_TLS_ROOT_CA=$(shell_quote_value "${root_ca}")"
    echo "ZENOH_TLS_LISTEN_KEY=$(shell_quote_value "${listen_key}")"
    echo "ZENOH_TLS_LISTEN_CERT=$(shell_quote_value "${listen_cert}")"
    echo "ZENOH_TLS_VERIFY_NAME=$(shell_quote_value "${ZENOH_TLS_VERIFY_NAME:-0}")"
    echo "ZENOH_AUTO_ENABLE_QUIC=$(shell_quote_value "1")"
  } > "${PROFILE_FILE}"
  chmod 600 "${PROFILE_FILE}" 2>/dev/null || true
}

generate_server_cert() {
  if ! command -v openssl >/dev/null 2>&1; then
    log_error "openssl is required for Zenoh QUIC TLS setup."
    return 1
  fi

  local dir key cert cfg cn days
  local dns_names=()
  local ip_names=()
  dir="$(tls_dir)"
  key="${ZENOH_TLS_LISTEN_KEY:-${dir}/zenoh.key.pem}"
  cert="${ZENOH_TLS_LISTEN_CERT:-${dir}/zenoh.cert.pem}"
  cfg="${dir}/openssl-san.cnf"
  days="${ZENOH_TLS_DAYS:-825}"
  mkdir -p "${dir}"
  chmod 700 "${dir}" 2>/dev/null || true

  add_unique dns_names "$(hostname -f 2>/dev/null || hostname)"
  add_unique dns_names "$(hostname 2>/dev/null || true)"
  add_unique dns_names "localhost"
  add_unique dns_names "${ZENOH_TLS_COMMON_NAME:-}"
  add_unique dns_names "${HORUS_CLOUD_IP:-}"
  add_unique dns_names "${HORUS_MACHINE_IP:-}"
  add_unique ip_names "127.0.0.1"
  add_unique ip_names "${HORUS_CLOUD_IP:-}"
  add_unique ip_names "${HORUS_MACHINE_IP:-}"
  for ip in $(hostname -I 2>/dev/null || true); do
    [[ "${ip}" == *:* ]] && continue
    add_unique ip_names "${ip}"
  done
  if [[ -n "${ZENOH_TLS_ALT_NAMES:-}" ]]; then
    IFS=',' read -ra alt_values <<< "${ZENOH_TLS_ALT_NAMES}"
    local alt
    for alt in "${alt_values[@]}"; do
      if is_ipv4 "$(normalize_host "${alt}")"; then
        add_unique ip_names "${alt}"
      else
        add_unique dns_names "${alt}"
      fi
    done
  fi

  local filtered_dns=()
  local item
  for item in "${dns_names[@]}"; do
    if is_ipv4 "${item}"; then
      add_unique ip_names "${item}"
    else
      filtered_dns+=("${item}")
    fi
  done
  dns_names=("${filtered_dns[@]}")
  cn="${ZENOH_TLS_COMMON_NAME:-${HORUS_CLOUD_IP:-${HORUS_MACHINE_IP:-${dns_names[0]:-horus-hub}}}}"
  cn="$(normalize_host "${cn}")"

  {
    echo "[req]"
    echo "distinguished_name=req_distinguished_name"
    echo "x509_extensions=v3_req"
    echo "prompt=no"
    echo "[req_distinguished_name]"
    echo "CN=${cn}"
    echo "[v3_req]"
    echo "subjectAltName=@alt_names"
    echo "[alt_names]"
    local idx=1
    for item in "${dns_names[@]}"; do
      echo "DNS.${idx}=${item}"
      idx=$((idx + 1))
    done
    idx=1
    for item in "${ip_names[@]}"; do
      echo "IP.${idx}=${item}"
      idx=$((idx + 1))
    done
  } > "${cfg}"

  if [[ -f "${key}" && -f "${cert}" && "${ZENOH_TLS_REGENERATE:-0}" != "1" ]]; then
    log_success "Zenoh TLS certificate already exists."
  else
    openssl req -x509 -newkey rsa:3072 -sha256 -days "${days}" -nodes \
      -keyout "${key}" \
      -out "${cert}" \
      -config "${cfg}" >/dev/null 2>&1
    chmod 600 "${key}" "${cert}" 2>/dev/null || true
    log_success "Generated Zenoh QUIC TLS certificate."
  fi

  write_profile "${cert}" "${key}" "${cert}"
  log_info "Public cert: ${cert}"
  log_info "Profile: ${PROFILE_FILE}"
}

install_client_cert() {
  local source_cert="${2:-${ZENOH_TLS_ROOT_CA:-}}"
  if [[ -z "${source_cert}" ]]; then
    log_error "Missing certificate path."
    usage
    return 2
  fi
  source_cert="${source_cert/#\~/${HOME}}"
  if [[ ! -f "${source_cert}" ]]; then
    log_error "Certificate file does not exist: ${source_cert}"
    return 1
  fi

  local dir cert
  dir="$(tls_dir)"
  cert="${dir}/zenoh.root-ca.pem"
  mkdir -p "${dir}"
  chmod 700 "${dir}" 2>/dev/null || true
  cp "${source_cert}" "${cert}"
  chmod 600 "${cert}" 2>/dev/null || true
  write_profile "${cert}" "" ""
  log_success "Installed Zenoh QUIC root certificate."
  log_info "Root CA: ${cert}"
  log_info "Profile: ${PROFILE_FILE}"
}

show_status() {
  load_key_value_file "${PROFILE_FILE}"
  echo -e "\n${BOLD}${FG_CYAN}Zenoh QUIC TLS${RESET}"
  echo -e "  profile    ${PROFILE_FILE}"
  echo -e "  root ca    ${ZENOH_TLS_ROOT_CA:-${FG_MUTED}-${RESET}}"
  echo -e "  cert       ${ZENOH_TLS_LISTEN_CERT:-${FG_MUTED}-${RESET}}"
  echo -e "  key        ${ZENOH_TLS_LISTEN_KEY:-${FG_MUTED}-${RESET}}"
  echo -e "  verify     ${ZENOH_TLS_VERIFY_NAME:-0}"
  echo ""
}

load_key_value_file "${ENV_FILE}"
load_key_value_file "${PROFILE_FILE}"

case "${ACTION}" in
  auto)
    case "${HORUS_ROLE:-machine}" in
      cloud) generate_server_cert ;;
      machine)
        if [[ "${HORUS_TOPOLOGY:-hub}" == "direct" ]]; then
          generate_server_cert
        else
          show_status
        fi
        ;;
      robot) show_status ;;
      *) show_status ;;
    esac
    ;;
  server|listener)
    generate_server_cert
    ;;
  client|install)
    install_client_cert "$@"
    ;;
  status)
    show_status
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    log_error "Unknown action: ${ACTION}"
    usage
    exit 2
    ;;
esac
